In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/anemia-types-classification/diagnosed_cbc_data_v4.csv


In [2]:
df= pd.read_csv('/kaggle/input/anemia-types-classification/diagnosed_cbc_data_v4.csv')
df.head()

WBC  LYMp  NEUTp  LYMn  NEUTn   RBC  HGB    HCT   MCV   MCH  MCHC    PLT  \
0  10.0  43.2   50.1   4.3    5.0  2.77  7.3   24.2  87.7  26.3  30.1  189.0   
1  10.0  42.4   52.3   4.2    5.3  2.84  7.3   25.0  88.2  25.7  20.2  180.0   
2   7.2  30.7   60.7   2.2    4.4  3.97  9.0   30.5  77.0  22.6  29.5  148.0   
3   6.0  30.2   63.5   1.8    3.8  4.22  3.8   32.8  77.9  23.2  29.8  143.0   
4   4.2  39.1   53.7   1.6    2.3  3.93  0.4  316.0  80.6  23.9  29.7  236.0   

    PDW   PCT                      Diagnosis  
0  12.5  0.17  Normocytic hypochromic anemia  
1  12.5  0.16  Normocytic hypochromic anemia  
2  14.3  0.14         Iron deficiency anemia  
3  11.3  0.12         Iron deficiency anemia  
4  12.8  0.22  Normocytic hypochromic anemia

In [3]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

In [4]:
y=df['Diagnosis']
x=df.drop('Diagnosis',axis=1)

In [5]:
y

0       Normocytic hypochromic anemia
1       Normocytic hypochromic anemia
2              Iron deficiency anemia
3              Iron deficiency anemia
4       Normocytic hypochromic anemia
                    ...              
1276                          Healthy
1277                          Healthy
1278                          Healthy
1279                          Healthy
1280                          Healthy
Name: Diagnosis, Length: 1281, dtype: object

In [6]:
le=LabelEncoder()
y=le.fit_transform(y)

In [7]:
y

array([5, 5, 1, ..., 0, 0, 0])

In [8]:
le.inverse_transform([4])

array(['Macrocytic anemia'], dtype=object)

In [9]:
y=to_categorical(y)

In [10]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [11]:
y[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [12]:
x_train, x_test, y_train, y_test=train_test_split(x,y,train_size=0.75,random_state=43)

In [13]:
model=Sequential()

model.add(Dense(64,activation="relu",input_dim=len(x.columns))) # if u want to chance dence
model.add(Dense(32,activation="relu"))
model.add(Dense(32,activation="relu"))

model.add(Dense(9,activation="softmax"))

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [14]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [15]:
model.fit(x_train,y_train,epochs =128,batch_size=32,validation_split=0.24)

Epoch 1/128
23/23 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.1072 - loss: 18.4753 - val_accuracy: 0.3074 - val_loss: 3.7782
Epoch 2/128
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2832 - loss: 3.6900 - val_accuracy: 0.4675 - val_loss: 2.8265
Epoch 3/128
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3615 - loss: 2.2836 - val_accuracy: 0.4459 - val_loss: 2.2283
Epoch 4/128
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3245 - loss: 1.9523 - val_accuracy: 0.3766 - val_loss: 2.3441
Epoch 5/128
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4146 - loss: 1.6284 - val_accuracy: 0.4329 - val_loss: 2.1292
Epoch 6/128
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4102 - loss: 1.6377 - val_accuracy: 0.3896 - val_loss: 2.1606
Epoch 7/128
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4406 - loss: 1.5345 - val_accuracy: 0.5238 - val_loss: 2.0629
Epoch 8/128
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4521 - loss: 1.4985 - val_accuracy: 0.5065 -

In [16]:
### burada ranstgele değerden bak model.predict([[9.4,34,58,2.8,4.3,3.3,8.8,32,78,24,26,155,15,0.17]])

In [17]:
tahmin = np.array([[9.4,34,58,2.8,4.3,3.3,8.8,32,78,24,26,155,15,0.17]])
sonuc=model.predict(tahmin)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step


In [18]:
np.argmax(sonuc)

5

In [19]:
le.inverse_transform([5])

array(['Normocytic hypochromic anemia'], dtype=object)